language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"

install: 
  - pip install -r requires.txt
  - pip install .
script:
  - simpbot conf -m -a
  - simpbot server -a localhost
  - simpbot --start --no-daemon -d 10
